# Copyright (C) DATADVANCE, 2010-2018

# GitLab CI configuration.

# Documentations:
# https://docs.gitlab.com/ce/ci/yaml/README.html
# List of available environment variables:
# https://docs.gitlab.com/ce/ci/variables/README.html

# CI stages.
stages:
    - build
    - pages

variables:
    PIP_PROXY: http://nexus.macros:8081/repository/pypi-proxy/simple/

build_&_test:
    stage: build
    script:
        - |
            pip config set global.index-url $PIP_PROXY
            pip config set global.trusted-host $(echo $PIP_PROXY | awk -F[/:] '{print $4}')
            pip install --progress-bar off poetry
            poetry install
            poetry build
            poetry run pytest --cov-format=term --cov-format=html
    coverage: '/\d+\%\s*$/'
    artifacts:
        paths:
            - dist/
            - htmlcov/
        expire_in: 30 days
    tags:
        - python3.7

pages:
    stage: pages
    script:
        - mkdir -p public
        - cp -rf htmlcov/* public/
    artifacts:
        paths:
            - public/
        expire_in: 30 days
    only:
        - master
