# Copyright (C) DATADVANCE, 2010-2020
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# The Pre-commit configuration.
# https://pre-commit.com

repos:
    # The Black: Python code formatter.
    # https://black.readthedocs.io/
    - repo: local
      hooks:
          - description: "Black: The uncompromising Python code formatter"
            entry: black
            id: black
            language_version: python3.7
            language: python
            name: black
            require_serial: true
            types: [python]
            additional_dependencies: ["black"]

    # Isort: Sort Python imports.
    # https://github.com/timothycrosley/isort
    - repo: local
      hooks:
          - description: "Isort: Python import statements formatter"
            entry: isort
            id: isort
            language_version: python3.7
            language: python
            name: isort
            require_serial: false
            types: [python]
            additional_dependencies: ["isort[pyproject]"]
