# Copyright (C) DATADVANCE, 2010-2020
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Travis CI configuration.

jobs:
    include:
        - name: "Python 3.7 on Xenial Linux"
          os: linux
          python: "3.7" # Works in Linux, ignored in macOS and Windows.
          dist: xenial
          language: python
          before_install:
              - sudo apt-get update
              - sudo apt-get install -y enchant
          install:
              - pip3 install --upgrade pip
              - pip3 install --progress-bar off poetry
              - python3 -m poetry --no-interaction install
              - python3 -m poetry --no-interaction build
          script:
              - python3 -m poetry run pytest -n 8 --cov-report=term --cov-report=html
        - name: "Python 3.7 on macOS"
          os: osx
          osx_image: xcode10.2 # Python 3.7.2 running on macOS 10.14.3.
          python: "3.7"
          language: shell # 'Language: python' gives error here.
          before_install:
              - sudo apt-get update
              - sudo apt-get install -y enchant
          install:
              - pip3 install --upgrade pip
              - pip3 install --progress-bar off poetry
              - python3 -m poetry --no-interaction install
              - python3 -m poetry --no-interaction build
          script:
              - python3 -m poetry run pytest -n 8 --cov-report=term --cov-report=html
        - name: "Python 3.7 on Windows"
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
          os: windows # Windows 10.0.17134 N/A Build 17134
          language: shell # 'Language: python' gives error here.
          before_install:
              - choco install python -y
          install:
              - python -m pip install --upgrade pip
              - python -m pip install --progress-bar off poetry
              - python -m poetry --no-interaction install
              - python -m poetry --no-interaction build
          script:
              - python -m poetry run pytest -n 8 --cov-report=term --cov-report=html
