# Copyright (C) DATADVANCE, 2010-2020
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Travis CI configuration.

jobs:
    include:
        - name: "Python 3.6 on Xenial Linux"
          os: linux
          dist: xenial
          language: python
          python: "3.6"
          before_install:
              - python --version
              - python -m pip install --upgrade pip
              - python -m pip install poetry
          install:
              - python -m poetry install --no-interaction --verbose
          script:
              - python -m poetry run pytest --cov-report=term --cov-report=html

        - name: "Python 3.7 on Xenial Linux"
          os: linux
          dist: xenial
          language: python
          python: "3.7"
          before_install:
              - python --version
              - python -m pip install --upgrade pip
              - python -m pip install poetry
          install:
              - python -m poetry install --no-interaction --verbose
          script:
              - python -m poetry run pytest --cov-report=term --cov-report=html

        - name: "Python 3.8 on Xenial Linux"
          os: linux
          dist: xenial
          language: python
          python: "3.8"
          before_install:
              - python --version
              - python -m pip install --upgrade pip
              - python -m pip install poetry
          install:
              - python -m poetry install --no-interaction --verbose
          script:
              - python -m poetry run pytest --cov-report=term --cov-report=html

        - name: "Python 3.7.4 on MacOS"
          os: osx
          osx_image: xcode11.2 # Python 3.7.4 running on MacOS 10.14.4.
          language: shell
          before_install:
              - python3 --version
              - python3 -m pip install --upgrade pip
              - python3 -m pip install poetry
          install:
              - python3 -m poetry install --no-interaction --verbose
          script:
              - python3 -m poetry run pytest --cov-report=term --cov-report=html

        - name: "Python 3.7.7 on Windows"
          os: windows
          language: shell
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
          before_install:
              - choco install python --version 3.7.7 --no-progress
              - python --version
              - python -m pip install --upgrade pip
              - python -m pip install poetry
          install:
              - python -m poetry install --no-interaction --verbose
          script:
              - python -m poetry run pytest --cov-report=term --cov-report=html

        - name: "Python 3.8.2 on Windows"
          os: windows
          language: shell
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
          before_install:
              - choco install python --version 3.8.2 --no-progress
              - python --version
              - python -m pip install --upgrade pip
              - python -m pip install poetry
          install:
              - python -m poetry install --no-interaction --verbose
          script:
              - python -m poetry run pytest --cov-report=term --cov-report=html
